[project]
name = "trading-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lnmarkets-sdk @ git+https://github.com/ln-markets/sdk-python.git@main",
    "pyaml>=6.0",
    "tradingview-ta>=3.2.9",
    "pandas>=1.4.2",
    "ccxt>=4.0.0",
    "matplotlib>=3.0.0",
    "backtesting>=0.6.5",
]

[project.scripts]
trading-bot = "main:main"
